#!/usr/bin/make
# please update doc/md/packages/extras.md after adding changes to this file
WGET=wget --continue --no-verbose --show-progress --directory-prefix=cache/downloads/

all: download_extra

clean:
	rm -rvf config/packages.chroot/
	rm -rvf cache/downloads
	rm -rf config/includes.chroot/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}

clean_all: clean
	rm -rvf cache/downloads/


download_extra: clean
	# Download additional software from third-party repository (https://nodiscc.gitlab.io/toolbox)
	# TODO use the APT repository at build time, but disable it in the final chroot/image
	# TODO file ITPs on bugs.debian.org
	mkdir -p cache/downloads/ config/packages.chroot/

	# EXTRA https://github.com/az0/cleanerml
	$(WGET) https://nodiscc.gitlab.io/toolbox/pool/main/b/bleachbit-cleanerml/bleachbit-cleanerml_0.0.1~git0+5bc2961_all.deb
	mkdir -p root/tmp/extra_packages
	cp cache/downloads/bleachbit-cleanerml_0.0.1~git0+5bc2961_all.deb root/tmp/extra_packages/

	# ... (disabled sections omitted for brevity if unchanged logic, but keeping clean structure)

	# EXTRA https://github.com/nodiscc/user.js
	$(WGET) https://nodiscc.gitlab.io/toolbox/pool/main/u/user.js/user.js_0.13.0-1_all.deb
	cp cache/downloads/user.js_0.13.0-1_all.deb root/tmp/extra_packages/

	mkdir -p root/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}
	# EXTRA https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/
	$(WGET) https://addons.mozilla.org/firefox/downloads/file/3711829/cookie_autodelete-3.6.0-an+fx.xpi -O root/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/CookieAutoDelete@kennydo.com.xpi

	# EXTRA https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/
	mkdir -p root/usr/lib/thunderbird/extensions/
	$(WGET) https://addons.thunderbird.net/thunderbird/downloads/latest/gmail-conversation-view/addon-54035-latest.xpi -O root/usr/lib/thunderbird/extensions/gconversation@xulforum.org.xpi
