default debian
label debian
    kernel /boot/vmlinuz-*-asus-tf101
    initrd /boot/initrd.img-*-asus-tf101
    append root=/dev/mmcblk0p2 rw rootwait console=tty1 quiet
    fdtdir /usr/lib/linux-image-*-asus-tf101/
